/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueryIndexRouteImport } from './routes/query/index'
import { Route as QueryQuerySubRouteImport } from './routes/query/query-sub'
import { Route as RouterIndexRouteImport } from './routes/router/index'
import { Route as RouterRouterSubRouteImport } from './routes/router/router-sub'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryIndexRoute = QueryIndexRouteImport.update({
  id: '/query/',
  path: '/query/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryQuerySubRoute = QueryQuerySubRouteImport.update({
  id: '/query/query-sub',
  path: '/query/query-sub',
  getParentRoute: () => rootRouteImport,
} as any)
const RouterIndexRoute = RouterIndexRouteImport.update({
  id: '/router/',
  path: '/router/',
  getParentRoute: () => rootRouteImport,
} as any)
const RouterRouterSubRoute = RouterRouterSubRouteImport.update({
  id: '/router/router-sub',
  path: '/router/router-sub',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/query/query-sub': typeof QueryQuerySubRoute
  '/router/router-sub': typeof RouterRouterSubRoute
  '/query/': typeof QueryIndexRoute
  '/router/': typeof RouterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/query/query-sub': typeof QueryQuerySubRoute
  '/router/router-sub': typeof RouterRouterSubRoute
  '/query': typeof QueryIndexRoute
  '/router': typeof RouterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/query/query-sub': typeof QueryQuerySubRoute
  '/router/router-sub': typeof RouterRouterSubRoute
  '/query/': typeof QueryIndexRoute
  '/router/': typeof RouterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/query/query-sub' | '/router/router-sub' | '/query/' | '/router/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/query/query-sub' | '/router/router-sub' | '/query' | '/router'
  id:
    | '__root__'
    | '/'
    | '/query/query-sub'
    | '/router/router-sub'
    | '/query/'
    | '/router/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QueryQuerySubRoute: typeof QueryQuerySubRoute
  RouterRouterSubRoute: typeof RouterRouterSubRoute
  QueryIndexRoute: typeof QueryIndexRoute
  RouterIndexRoute: typeof RouterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query/': {
      id: '/query/'
      path: '/query'
      fullPath: '/query/'
      preLoaderRoute: typeof QueryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query/query-sub': {
      id: '/query/query-sub'
      path: '/query/query-sub'
      fullPath: '/query/query-sub'
      preLoaderRoute: typeof QueryQuerySubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/router/': {
      id: '/router/'
      path: '/router'
      fullPath: '/router/'
      preLoaderRoute: typeof RouterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/router/router-sub': {
      id: '/router/router-sub'
      path: '/router/router-sub'
      fullPath: '/router/router-sub'
      preLoaderRoute: typeof RouterRouterSubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QueryQuerySubRoute: QueryQuerySubRoute,
  RouterRouterSubRoute: RouterRouterSubRoute,
  QueryIndexRoute: QueryIndexRoute,
  RouterIndexRoute: RouterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
